-- MSmatematika production schema
create extension if not exists pgcrypto;

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete restrict,
  variant int not null check (variant between 1 and 20),
  surname text not null,
  first_name text not null,
  phone text not null,
  started_at timestamptz not null,
  submitted_at timestamptz not null default now(),
  duration_seconds int not null check (duration_seconds between 0 and 9000),
  parent_correct int check (parent_correct between 0 and 45),
  item_correct int check (item_correct between 0 and 55),
  item_total int not null default 55,
  rasch_theta double precision,
  ms_score numeric(5,2),
  level text,
  rasch_status text not null default 'collecting',
  status text not null default 'completed' check (status in ('completed')),
  created_at timestamptz not null default now()
);

create index if not exists attempts_owner_idx on public.attempts(owner_id, submitted_at desc);
create index if not exists attempts_variant_idx on public.attempts(variant, submitted_at desc);

create table if not exists public.attempt_items (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.attempts(id) on delete restrict,
  owner_id uuid not null references auth.users(id) on delete restrict,
  variant int not null check (variant between 1 and 20),
  item_code text not null,
  question_num int not null check (question_num between 1 and 45),
  subpart text check (subpart in ('a','b') or subpart is null),
  response text,
  is_correct boolean not null,
  created_at timestamptz not null default now(),
  unique(attempt_id,item_code)
);

create index if not exists attempt_items_variant_item_idx on public.attempt_items(variant,item_code);
create index if not exists attempt_items_owner_idx on public.attempt_items(owner_id,attempt_id);

-- Answer keys live in the database, not in the public GitHub site.
create table if not exists public.answer_keys (
  id bigint generated by default as identity primary key,
  variant int not null check (variant between 1 and 20),
  question_num int not null check (question_num between 1 and 45),
  subpart text check (subpart in ('a','b') or subpart is null),
  answer_type text not null check (answer_type in ('choice','math')),
  answer_raw text not null,
  display_latex text,
  check_mode text not null default 'equivalent'
    check (check_mode in ('equivalent','exact')),
  unique nulls not distinct (variant, question_num, subpart)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.attempts enable row level security;
alter table public.attempt_items enable row level security;
alter table public.answer_keys enable row level security;
alter table public.admin_users enable row level security;

-- Students may only read their own immutable result history.
drop policy if exists "read own attempts" on public.attempts;
create policy "read own attempts" on public.attempts for select to authenticated using (auth.uid() = owner_id);

drop policy if exists "read own attempt items" on public.attempt_items;
create policy "read own attempt items" on public.attempt_items for select to authenticated using (auth.uid() = owner_id);

-- No INSERT/UPDATE/DELETE policies for attempts/items: only Edge Functions with service role write them.
-- No policies at all for answer_keys/admin_users: browser clients cannot read them.

revoke all on public.answer_keys from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;
grant select on public.attempts to authenticated;
grant select on public.attempt_items to authenticated;
